import { createHmac } from "node:crypto";
import { env } from "../../env";

/**
 * Fonepay dynamic QR (third-party merchant API).
 *
 *   POST {apiBase}/thirdPartyDynamicQrDownload
 *     { amount, remarks1, remarks2, prn, merchantCode, dataValidation, username, password }
 *     dataValidation = HMAC-SHA512(secretKey, "amount,prn,merchantCode,remarks1,remarks2") hex
 *     → { success, qrMessage, ... }   qrMessage is the EMVCo payload to render as a QR
 *
 *   POST {apiBase}/thirdPartyDynamicQrGetStatus
 *     { prn, merchantCode, dataValidation, username, password }
 *     dataValidation = HMAC-SHA512(secretKey, "prn,merchantCode") hex
 *     → { paymentStatus: "success" | "pending" | "failed", fonepayTraceId, ... }
 *
 * Credentials come from Fonepay / the acquiring bank and live only in the
 * server environment. The QR payload is generated by Fonepay, never by us.
 */
export interface DynamicQr {
  qrMessage: string;
}
export interface QrStatus {
  status: "success" | "pending" | "failed";
  traceId: string | null;
}

export class FonepayError extends Error {}

export function fonepayEnabled(): boolean {
  const f = env.fonepay;
  if (f.mode === "mock") return true;
  return f.mode === "live" && Boolean(f.merchantCode && f.username && f.password && f.secretKey);
}

export function sign(secret: string, parts: (string | number)[]): string {
  return createHmac("sha512", secret).update(parts.join(",")).digest("hex");
}

/** Remarks are printed on statements; keep them short and plain. */
export function cleanRemark(s: string): string {
  return s.replace(/[^A-Za-z0-9 -]/g, "").slice(0, 25).trim();
}

async function post<T>(path: string, body: Record<string, unknown>): Promise<T> {
  const res = await fetch(`${env.fonepay.apiBase}/${path}`, {
    method: "POST",
    headers: { "content-type": "application/json", accept: "application/json" },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(15000),
  });
  const text = await res.text();
  let data: unknown;
  try {
    data = JSON.parse(text);
  } catch {
    throw new FonepayError(`Fonepay ${path}: HTTP ${res.status}, non-JSON response`);
  }
  if (!res.ok) throw new FonepayError(`Fonepay ${path}: HTTP ${res.status} ${(data as { message?: string }).message ?? ""}`.trim());
  return data as T;
}

// ---- mock (development / tests) -------------------------------------------
const mockPaid = new Map<string, string>();
/** Test/dev helper: mark a PRN as paid in mock mode. */
export function mockMarkPaid(prn: string, traceId = `MOCK${Date.now()}`): void {
  mockPaid.set(prn, traceId);
}

export async function createDynamicQr(input: { amountNpr: number; prn: string; remarks1: string; remarks2: string }): Promise<DynamicQr> {
  const f = env.fonepay;
  const amount = String(input.amountNpr);
  const remarks1 = cleanRemark(input.remarks1);
  const remarks2 = cleanRemark(input.remarks2);
  if (f.mode === "mock") return { qrMessage: `MOCKFONEPAY|${input.prn}|${amount}|${remarks1}` };
  const data = await post<{ success?: boolean; qrMessage?: string; message?: string; status?: string }>("thirdPartyDynamicQrDownload", {
    amount,
    remarks1,
    remarks2,
    prn: input.prn,
    merchantCode: f.merchantCode,
    dataValidation: sign(f.secretKey, [amount, input.prn, f.merchantCode, remarks1, remarks2]),
    username: f.username,
    password: f.password,
  });
  if (!data.success || !data.qrMessage) throw new FonepayError(`Fonepay QR not created: ${data.message ?? data.status ?? "unknown error"}`);
  return { qrMessage: data.qrMessage };
}

export async function getQrStatus(prn: string): Promise<QrStatus> {
  const f = env.fonepay;
  if (f.mode === "mock") {
    const t = mockPaid.get(prn);
    return t ? { status: "success", traceId: t } : { status: "pending", traceId: null };
  }
  const data = await post<{ paymentStatus?: string; fonepayTraceId?: string | number; prn?: string }>("thirdPartyDynamicQrGetStatus", {
    prn,
    merchantCode: f.merchantCode,
    dataValidation: sign(f.secretKey, [prn, f.merchantCode]),
    username: f.username,
    password: f.password,
  });
  if (data.prn && data.prn !== prn) throw new FonepayError("Fonepay status response is for a different PRN");
  const s = String(data.paymentStatus ?? "").toLowerCase();
  const status: QrStatus["status"] = s === "success" ? "success" : s === "failed" ? "failed" : "pending";
  return { status, traceId: data.fonepayTraceId != null ? String(data.fonepayTraceId) : null };
}
